name: jarvis
description: A Voice Assistant App.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  speech_to_text: ^6.1.1
  flutter_tts: ^3.6.3
  animate_do: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/open_ai.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Cera Pro
      fonts:
        - asset: assets/fonts/Cera-Pro-Bold.otf
        - asset: assets/fonts/Cera-Pro-Medium.otf
 
